[package]
name = "day22"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
anyhow = "1.0.40"
intersection_detection = "0.1.3"
rand = "0.8.5"

[dependencies.uuid]
version = "1.6.1"
features = [ 
    "v4"
]